name: TV Guide and Playlist Generator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 3 */2 * *'  # Run at 3am every 48 hours
  workflow_dispatch:

jobs:
  generate_files:
    name: Generate TV Guide and Playlists
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install Python dependencies
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz selenium webdriver-manager selenium-stealth

      # Set up Chrome for Selenium
      - name: Set up Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends google-chrome-stable

      # Generate XML EPG file
      - name: Generate XML EPG
        run: |
          mkdir -p en
          python py/videoxml.py > en/videoall.xml
        env:
          TZ: America/New_York

      # Generate M3U playlists
      - name: Generate M3U Playlists
        run: |
          mkdir -p en
          python py/videolivetv.py > en/videoall.m3u
          # Create a copy with alternative name if needed
          cp en/videoall.m3u en/videolivetv.m3u

      # Commit and push changes
      - name: Commit and push updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update TV guide and playlists"
          branch: main
          file_pattern: |
            en/videoall.xml
            en/videoall.m3u
            en/videolivetv.m3u
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
