name: TV Guide and Playlist Generator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *'  # Run every 2 hours
  workflow_dispatch:

jobs:
  generate_files:
    name: Generate TV Guide and Playlists
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install Python dependencies
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pytz selenium webdriver-manager selenium-stealth

      # Set up Chrome for Selenium
      - name: Set up Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends google-chrome-stable

      # Generate XML EPG file with current timestamp
      - name: Generate XML EPG
        run: |
          mkdir -p en
          TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
          echo "<!-- Generated at: $TIMESTAMP -->" > en/videoall.xml
          python py/videoxml.py >> en/videoall.xml

      # Generate M3U playlists with current timestamp
      - name: Generate M3U Playlists
        run: |
          mkdir -p en
          TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
          
          # Generate the M3U file with timestamp
          echo "#EXTM3U" > en/videoall.m3u
          echo "# Last Updated: $TIMESTAMP" >> en/videoall.m3u
          
          # Run the script and clean the output
          python py/videolivetv.py | grep -v '^<' | grep -v '^$' | grep -v '^\s*$' | grep -v '^\s*#' >> en/videoall.m3u
          
          # Create a copy with alternative name
          cp en/videoall.m3u en/videolivetv.m3u
          
          # Verify the files
          echo "Generated files:"
          ls -la en/
          echo "\nFirst few lines of videoall.m3u:"
          head -n 5 en/videoall.m3u || true

      # Force commit and push updates
      - name: Force commit and push updates
        run: |
          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Get current timestamp
          TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
          
          # Add and force commit
          git add en/videoall.xml en/videoall.m3u en/videolivetv.m3u
          git commit -m "Auto-update TV guide and playlists - $TIMESTAMP" --allow-empty
          
          # Force push to update the branch
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
          
          echo "Files updated and pushed at $TIMESTAMP"
